name: tests

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: ['8.1','8.2','8.3']
  
    steps:
      - name: Checkout codes
        uses: "actions/checkout@v2"

      - name: Composer
        uses: php-actions/composer@v6
        with:
          php_version: ${{ matrix.php }}
          php_extensions: gd

      - name: PHPUnit Tests
        uses: php-actions/phpunit@v3
        with:
          configuration: tests/phpunit.xml
          version: 10.5
          php_version: ${{ matrix.php }}
          php_extensions: gd
        env:
          TRAVIS_PHP_VERSION: true
